data:
  label: 'Churn'
  numerical: 
      - 'tenure'
      - 'MonthlyCharges' 
      - 'TotalCharges' 
  categorical: 
    - 'gender'
    - 'SeniorCitizen'
    - 'Partner'
    - 'Dependents' 
    - 'PhoneService' 
    - 'MultipleLines' 
    - 'InternetService' 
    - 'OnlineSecurity' 
    - 'OnlineBackup' 
    - 'DeviceProtection' 
    - 'TechSupport' 
    - 'StreamingTV' 
    - 'StreamingMovies' 
    - 'Contract' 
    - 'PaperlessBilling' 
    - 'PaymentMethod'
model:
    savepath: './churner/saved'
    name: 'churner_model.pkl'
inference:
    alert_threshold: 0.7